apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-prometheus-rule
spec:
  groups:
  - name: custom.alert.rules
    rules:
    - alert: HighFailedProbes
      expr: rate(probe_success{job="blackbox"}[1m]) < 1.0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "High number of failed probes"
        description: "More than 20% of probes have failed in the last minute"